site_name: Manga List API Dokumentation
site_author: Bennet
site_url: ""
use_directory_urls: False

nav:
  - 'index.md'
  - 'Endpoints.md'
  - 'Database.md'
  - 'Structs.md'
  - 'Herangehensweise.md'
  - 'Projektziele.md'
  - 'Code.md'

theme:
    features:
      - content.code.copy
      - navigation.tabs
      - navigation.sections
      - toc.integrate
      - navigation.top
      - search.suggest
      - search.highlight
      - content.tabs.link
      - content.code.annotation
      - content.code.copy
    name: material
    locale: de
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    palette:
      - scheme: default
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
        primary: teal
        accent: purple
      - scheme: slate
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
        primary: teal
        accent: lime

    plugins:
      - social



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BennetLe